package com.yash.trainingsys.model;



import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Training is the Model class to represent training data
 * 
 * @author snehal.pawar
 *
 */
@Entity
public class Training
//id,trainingName,requesterName,startDate,EndDate,
{
	/**
	 * Id of the Training which should be autogenerated
	 */
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	/**
	 * name of the training
	 */
	private String trainingName;
	/**
	 * Training requester name
	 */
	private String requesterName;
	/**
	 * start date of the training
	 */

	private Date startDate;
	/**
	 * Description of the training
	 */
	private String description;
	/**
	 * end date of the training
	 */
	private Date endDate;
	/**
	 * date of the Training data creation
	 */
	private Date createdAt;
	/**
	 * date of the updation performed on training data
	 */
	private Date updatedAt;
	

	public Training() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Training(Long id, String trainingName, String requesterName, Date startDate, String description,
			Date endDate, Date createdAt, Date updatedAt) {
		super();
		this.id = id;
		this.trainingName = trainingName;
		this.requesterName = requesterName;
		this.startDate = startDate;
		this.description = description;
		this.endDate = endDate;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTrainingName() {
		return trainingName;
	}

	public void setTrainingName(String trainingName) {
		this.trainingName = trainingName;
	}

	public String getRequesterName() {
		return requesterName;
	}

	public void setRequesterName(String requesterName) {
		this.requesterName = requesterName;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Override
	public String toString() {
		return "Training [id=" + id + ", trainingName=" + trainingName + ", requesterName=" + requesterName
				+ ", startDate=" + startDate + ", description=" + description + ", endDate=" + endDate + ", createdAt="
				+ createdAt + ", updatedAt=" + updatedAt + "]";
	}

}

	

